### ISSUE TITLE
simple_setup.py unable to find "config/DeviceList.json" when it installs json parser

### ISSUE THREAD

**Issue by KaushikNeelichetty** [dgitz/eros#188]
When json parser is not installed before running simple_setup.py , the following [conditional branch](https://github.com/dgitz/eros/blob/master/scripts/simple_setup.py#L48) is executed 

[This line of code](https://github.com/dgitz/eros/blob/18d4cee96b852b4a225ad23a7b85605257ad0207/scripts/simple_setup.py#L56) changes the working directory to `home + "/other_packages/json/build"`

Due to which the [file read](https://github.com/dgitz/eros/blob/18d4cee96b852b4a225ad23a7b85605257ad0207/scripts/simple_setup.py#L62) of `config/DeviceList.json` happens in `home + "/other_packages/json/build"` as opposed to the intended `eros/` directory. 

This causes the python script to fail with 

```
Running Simple Setup...
Creating Directories...
Installing Dependencies via apt...
Installing other dependencies from source...
Generating Default Config Files...
Traceback (most recent call last):
  File "scripts/simple_setup.py", line 77, in <module>
    main()
  File "scripts/simple_setup.py", line 73, in main
    run_setup()
  File "scripts/simple_setup.py", line 60, in run_setup
    with open("config/" + config_file_list[i], 'r') as in_file:
IOError: [Errno 2] No such file or directory: 'config/DeviceList.json'
```

**Comment by dgitz** [comment]
@KaushikNeelichetty This is fixed as of commit: 9d51fe2b546a3fc1d926fada6bbc05b71d69a290.  If you don't wish to update your eros content, I've found that you can resolve this issue by simply running the simple_setup.py script twice.
